version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: casemgr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/casemgr
      ALERT_THRESHOLD: 100000
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
