apiVersion: v1
kind: Service
metadata:
  name: case-manager-svc
spec:
  selector:
    app: case-manager
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
