name: Build and Deploy to AKS

on:
  push:
    branches: [ "main" ]

env:
  ACR_NAME: myregistry
  AKS_CLUSTER: myaks
  AKS_RESOURCE_GROUP: my-rg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/case-manager:${{ github.sha }} ./trade-ingest

      - name: Push Docker image
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login $ACR_NAME.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push $ACR_NAME.azurecr.io/case-manager:${{ github.sha }}

      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER
          helm upgrade --install case-manager ./charts/case-manager \
            --set image.repository=$ACR_NAME.azurecr.io/case-manager \
            --set image.tag=${{ github.sha }}
